INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (3, '判断题内容', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (5, '数据库管理系统设计不是DBA数据库管理员的职责 ', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (6, '数据库的概念模型独立于  具体的机器和DBMS  ', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (17, '子模式是用户或应用程序看到的那部分局部逻辑结构和特征的描述', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (18, '描述数据库全体数据的全局逻辑结构和特性的是外模式', '错');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (19, '数据库的基本特点是(1)数据结构化 (2)数据独立性  (3)数据共享性高，冗余小，易扩充   (4)统一管理和控制', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (20, '1．在下列选项中,不同的列应有不同的数据类型不是基本关系的性质。', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (25, 'SQL中的视图提高了数据库系统的安全性', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (28, '物体运动状态改变时，一定受到力的作用', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (31, '浴室脚垫做得凹凸不平目的是为了减小摩擦', '错');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (32, '飞轮绕定轴作匀速转动时，飞轮边缘上任一点的切向加速度为零,法向加速度不为零', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (33, 'SQL中的视图机制提高了数据库系统的安全性', '对');
INSERT INTO qbms.judgment_question (judgment_id, judgment_content, judgment_answer) VALUES (34, '123123爱的方式打赏', '错');
